---
title: "FaceDetection"
author: "Yanyu Zheng yz2690"
date: "March 6, 2016"
output: html_document
---
# Basic setup
```{r}
setwd("~/Data Science/Project3/cycle3cvd-team2/data")
lib = c("EBImage", "XML","dplyr","adabag")
lapply(lib, library, character.only = TRUE)
func = c("abstracPatch.R",	"findPatch.R",	"scorePatch.R", "cropBack.R",	"getFace.R",		"scorePatchList.R",	"meanFace.R",		"standardFace.R", "cropBoundary.R",	"readIn.R", "readInHead.R","rescale.R","findFace.R","testFace.R","randomBack.R", "makePatchList.R") 
func = paste("../lib/",func,sep="") 
lapply(func, source)
dir_images = "../../data_train"
dir_names <- list.files(dir_images)
```

# Get class
```{r}
breed_name = sapply(dir_names,gsub,pattern = "\\_[0-9].*",replacement = "")
cat_breed <- c("Abyssinian", "Bengal", "Birman", "Bombay", "British_Shorthair", "Egyptian_Mau","Maine_Coon", "Persian", "Ragdoll", "Russian_Blue", "Siamese", "Sphynx")

iscat <- breed_name %in% cat_breed
y_cat <- as.numeric(iscat)
```

# Get the face
```{r}
dir_XML = "../../annotations/xmls"
dir_ann = list.files(dir_XML)
dir_names = lapply(dir_ann, gsub, pattern = ".xml", replacement = "")
# dir_names = head(dir_names)
lapply(dir_names,getFace,xmlDir = "../../annotations/xmls",picDir = "../../images",CatDir = "../../Faces/Cat",DogDir = "../../Faces/Dog")
```

# Crop background
```{r}
names = sample(dir_names,100)
pics = lapply(names, readIn, picDir = "../../images")
boundary = sapply(pics, cropBack,step=2,thresholdRatio=0.35,thresholdC=0.95)
```

# Find features
```{r}
## Pick up all train heads
dirCatFaces = "../../faces/cat"
dirDogFaces = "../../faces/dog"
catNames = list.files(dirCatFaces)
isTrain = catNames %in% dir_names
catNames = catNames[isTrain]
dogNames = list.files(dirDogFaces)
isTrain = dogNames %in% dir_names
dogNames = dogNames[isTrain]
## Standard cat face for patches
catSFace = catNames %>%
  standardFace(picDir = dirCatFaces,discard = TRUE) 
## Pick up patches
patch = vector("list",length = 3)
patch[[1]] = catSFace%>%
  lapply(abstractPatch, xmin = 0, ymin = 0, xmax = 30, ymax = 30)
patch[[2]] = catSFace%>%
  lapply(abstractPatch, xmin = 70, ymin = 70, xmax = 100, ymax = 100)
patch[[3]] = catSFace%>%
  lapply(abstractPatch, xmin = 20, ymin = 40, xmax = 80, ymax = 60)
catPatchs = c(patch1,patch2,patch3)
catPatchs = patch3
#print("patch finished")

catTestList = sample(catNames,100)
catTestPic = standardFace(catTestList,picDir = dirCatFaces,discard = FALSE)
catScores = t(sapply(catTestPic,FUN = scorePatchList,patchList = catPatchs))
print("cat score finished")

dogTestList = sample(dogNames,length(catTestPic))
dogTestPic = standardFace(dogTestList,picDir =  dirDogFaces,discard = FALSE)
dogScores = t(sapply(dogTestPic,FUN = scorePatchList,patchList = catPatchs))
print("dogscore finished")

backTestList = sample(dir_names,length(catTestPic))
backTestPic = lapply(backTestList,randomBack,picDir = dir_images) 
backScores = t(sapply(backTestPic,FUN = scorePatchList,patchList = catPatchs))

scores = rbind(catScores,backScores)
dataTest = data.frame(group = as.factor(rep(c(0,1),each = length(catTestPic))),scores)

play = bagging(group~., dataTest,mfinal=30)

importanceplot(play)
plot(sort(play$importance,TRUE)[1:50])
sort(play$importance,TRUE)[1:2]
plot(scores[,243])
display(catPatchs[[243]][[1]])
display(catPatchs[[271]][[1]])

patchUsed1 = c(301, 337, 65)
playPatchs1 = makePatchList(patch1,scores[1],patchUsed1)
patchUsed2 = c(598,57)
playPatchs2 = makePatchList(patch2,scores[2],patchUsed2)
patchUsed3 = c(243,271)
playPatchs3 = makePatchList(patch3,scores[3],patchUsed3)
```

# Find face
```{r}
playPatchs = c(playPatchs1,playPatchs2,playPatchs3)

picPlay = sample(catNames,1)%>%
  readIn(picDir = dir_images)
  
findFace(picPlay,playPatchs,"../")
 
```

# Waste Codes
```{r}
###########
##breedList
###########
# breedName = sapply(dirFaceNames,gsub,pattern = "\\_[0-9].*",replacement = "")
# breedList <- vector("list", length(cat_breed))
# names(breedList) <- cat_breed
# for (i in 1:length(cat_breed)){
#   breedList[[cat_breed[i]]] = dirFaceNames[breedName == cat_breed[[i]]]
# }

###########
##meanface
###########
# play = meanFace(abyssinian,5)
# play = ifelse(abyssinian[[1]]>median(abyssinian[[1]]),0,1)
# #play = ifelse(play>median(play),0,1)
# display(play)
```

